(define (domain lightsout_rgb)
(:types cell)
(:predicates
	(W ?c - cell)
	(R ?c - cell)
	(G ?c - cell)
	(B ?c - cell)
	(tipo0 ?c - cell)
	(tipo1 ?c - cell)
	(tipo2 ?c - cell)
	(tipo3 ?c - cell)
	(tipo4 ?c - cell)
	(same_row ?c1 ?c2 - cell)
	(same_col ?c1 ?c2 - cell)
)
(:action click
	:parameters (?c - cell)
	:effect
		(and
			(when (and (not (tipo1 ?c)) (W ?c)) (and (not (W ?c)) (R ?c)))
			(when (and (not (tipo1 ?c)) (R ?c)) (and (not (R ?c)) (G ?c)))
			(when (and (not (tipo1 ?c)) (G ?c)) (and (not (G ?c)) (B ?c)))
			(when (and (not (tipo1 ?c)) (B ?c)) (and (not (B ?c)) (W ?c)))
			(forall (?a - cell)
				(and
					(when (same_row ?c ?a)
						(and
							(when (and (tipo0 ?a) (W ?a)) (and (not (W ?a)) (R ?a)))
							(when (and (tipo0 ?a) (R ?a)) (and (not (R ?a)) (G ?a)))
							(when (and (tipo0 ?a) (G ?a)) (and (not (G ?a)) (B ?a)))
							(when (and (tipo0 ?a) (B ?a)) (and (not (B ?a)) (W ?a)))
							(when (and (tipo1 ?a) (W ?a)) (and (not (W ?a)) (R ?a)))
							(when (and (tipo1 ?a) (R ?a)) (and (not (R ?a)) (G ?a)))
							(when (and (tipo1 ?a) (G ?a)) (and (not (G ?a)) (B ?a)))
							(when (and (tipo1 ?a) (B ?a)) (and (not (B ?a)) (W ?a)))
							(when (and (tipo2 ?a) (W ?a)) (and (not (W ?a)) (R ?a)))
							(when (and (tipo2 ?a) (R ?a)) (and (not (R ?a)) (G ?a)))
							(when (and (tipo2 ?a) (G ?a)) (and (not (G ?a)) (B ?a)))
							(when (and (tipo2 ?a) (B ?a)) (and (not (B ?a)) (W ?a)))
						)
					)
					(when (same_col ?c ?a) 
						(and
							(when (and (tipo0 ?a) (W ?a)) (and (not (W ?a)) (R ?a)))
							(when (and (tipo0 ?a) (R ?a)) (and (not (R ?a)) (G ?a)))
							(when (and (tipo0 ?a) (G ?a)) (and (not (G ?a)) (B ?a)))
							(when (and (tipo0 ?a) (B ?a)) (and (not (B ?a)) (W ?a)))
							(when (and (tipo1 ?a) (W ?a)) (and (not (W ?a)) (R ?a)))
							(when (and (tipo1 ?a) (R ?a)) (and (not (R ?a)) (G ?a)))
							(when (and (tipo1 ?a) (G ?a)) (and (not (G ?a)) (B ?a)))
							(when (and (tipo1 ?a) (B ?a)) (and (not (B ?a)) (W ?a)))
							(when (and (tipo3 ?a) (W ?a)) (and (not (W ?a)) (R ?a)))
							(when (and (tipo3 ?a) (R ?a)) (and (not (R ?a)) (G ?a)))
							(when (and (tipo3 ?a) (G ?a)) (and (not (G ?a)) (B ?a)))
							(when (and (tipo3 ?a) (B ?a)) (and (not (B ?a)) (W ?a)))
                        )
                    )
                )
            )
        )
	)
)
